"""
LLM-Based Corpus Generation for Semantic POVM Operators

Purpose: Rapidly generate high-quality exemplar texts using Claude API
- Generates 30-50 examples per axis (enough for operator learning)
- Uses axis definitions and keywords to guide generation
- Validates examples for quality and diversity

Usage:
  poetry run python generate_corpus_examples.py --pack tone --axis analytical --count 30
  poetry run python generate_corpus_examples.py --all  # Generate for all axes
"""

import sys
import os
import json
import asyncio
from pathlib import Path
from typing import List
import anthropic

# Add project root to path
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

from collect_corpus import (
    AXIS_DEFINITIONS,
    CorpusExample,
    load_corpus_axis,
    save_corpus_axis,
)


# ============================================================================
# LLM Generation
# ============================================================================

def create_generation_prompt(pack: str, axis: str, count: int = 30) -> str:
    """Create prompt for Claude to generate examples."""

    axis_config = AXIS_DEFINITIONS[pack][axis]
    description = axis_config['description']
    keywords = ', '.join(axis_config['keywords'])
    seed_examples = axis_config['examples']

    prompt = f"""Generate {count} diverse, high-quality example texts that exemplify the "{axis}" axis in the "{pack}" POVM pack.

**Axis Definition**: {description}

**Keywords**: {keywords}

**Seed Examples** (for reference):
{chr(10).join(f'{i+1}. {ex}' for i, ex in enumerate(seed_examples))}

**Requirements**:
1. Each example should be 1-3 sentences (10-100 words)
2. Examples should clearly exemplify the "{axis}" characteristic
3. Vary the topics, contexts, and styles
4. Include both simple and complex examples
5. Make examples realistic (could appear in actual text)
6. Ensure diversity in length, structure, and content

**Output Format**:
Return ONLY a JSON array of strings, nothing else. Example:
["Example text 1.", "Example text 2.", "Example text 3."]

Generate {count} examples now:"""

    return prompt


async def generate_examples_with_claude(pack: str, axis: str, count: int = 30) -> List[str]:
    """Generate examples using Claude API."""

    # Get API key
    api_key = os.getenv('CLAUDE_API_KEY')
    if not api_key:
        raise ValueError("CLAUDE_API_KEY environment variable not set")

    client = anthropic.Anthropic(api_key=api_key)

    # Create prompt
    prompt = create_generation_prompt(pack, axis, count)

    print(f"Generating {count} examples for {pack}/{axis} using Claude...")

    # Call Claude API
    message = client.messages.create(
        model="claude-sonnet-4-5-20250929",  # Claude 4.5 Sonnet
        max_tokens=4000,
        temperature=0.8,  # Higher temperature for diversity
        messages=[{
            "role": "user",
            "content": prompt
        }]
    )

    # Parse response
    response_text = message.content[0].text

    # Extract JSON array from response
    try:
        # Try to parse as JSON directly
        examples = json.loads(response_text)
    except json.JSONDecodeError:
        # If that fails, try to find JSON array in text
        import re
        match = re.search(r'\[.*\]', response_text, re.DOTALL)
        if match:
            examples = json.loads(match.group(0))
        else:
            raise ValueError(f"Could not parse Claude response as JSON: {response_text[:200]}")

    print(f"✅ Generated {len(examples)} examples")

    return examples


async def generate_and_save(pack: str, axis: str, count: int = 30):
    """Generate examples and add to corpus."""

    # Load existing corpus
    corpus_axis = load_corpus_axis(pack, axis)
    existing_count = len(corpus_axis.examples)

    print(f"\n{'='*80}")
    print(f"Generating examples for {pack}/{axis}")
    print(f"Existing: {existing_count} examples")
    print(f"Target: {existing_count + count} examples")
    print(f"{'='*80}\n")

    # Generate examples
    example_texts = await generate_examples_with_claude(pack, axis, count)

    # Add to corpus
    for text in example_texts:
        example = CorpusExample(
            text=text,
            source='llm_generated',
            source_id='claude-sonnet-4-5',
            quality_score=0.9,  # High quality from Claude
            notes='Generated by Claude 4.5 Sonnet'
        )
        corpus_axis.examples.append(example)

    # Save
    save_corpus_axis(corpus_axis)

    print(f"✅ Total examples now: {len(corpus_axis.examples)}\n")


async def generate_all_axes(examples_per_axis: int = 30):
    """Generate examples for all axes."""

    print("\n" + "="*80)
    print("GENERATING CORPUS FOR ALL AXES".center(80))
    print("="*80 + "\n")

    total_generated = 0

    for pack, axes in AXIS_DEFINITIONS.items():
        print(f"\n{'='*80}")
        print(f"PACK: {pack.upper()}")
        print(f"{'='*80}")

        for axis in axes.keys():
            try:
                await generate_and_save(pack, axis, examples_per_axis)
                total_generated += examples_per_axis

                # Small delay to avoid rate limiting
                await asyncio.sleep(2)

            except Exception as e:
                print(f"❌ Error generating {pack}/{axis}: {e}")
                continue

    print("\n" + "="*80)
    print("GENERATION COMPLETE".center(80))
    print(f"Total examples generated: {total_generated}".center(80))
    print("="*80 + "\n")


# ============================================================================
# Main CLI
# ============================================================================

async def main():
    """Main generation CLI."""
    import argparse

    parser = argparse.ArgumentParser(description='Generate corpus examples using Claude API')
    parser.add_argument('--pack', help='POVM pack name')
    parser.add_argument('--axis', help='Axis name')
    parser.add_argument('--count', type=int, default=30, help='Number of examples to generate')
    parser.add_argument('--all', action='store_true', help='Generate for all axes')

    args = parser.parse_args()

    if args.all:
        # Generate for all axes
        await generate_all_axes(examples_per_axis=args.count)

    elif args.pack and args.axis:
        # Generate for specific axis
        await generate_and_save(args.pack, args.axis, args.count)

    else:
        print("❌ Error: Specify either --all or both --pack and --axis")
        parser.print_help()


if __name__ == "__main__":
    asyncio.run(main())
